Hanu jenkins jacobbaek 200917
openinfradev/pipeline-library pull request #2
Opened 2020-09-17 04:31 UTC by jacobbaek

* 기존에 hard coding 되어 있던 taco-prod의 변수화 (provider 변수 추가)
* UserMap 추가 및 getOSParam()에서 User정보 분리 (password의 경우 특수문자 포함될수 있으며 특수문자로 인해 shell 상에서 의도치 않은 결과 출력됨)

2020-09-21 07:46 UTC, robertchoi80 requested changes
코멘트 남겼습니다.

2020-09-21 07:46 UTC, robertchoi80 commented on createOpenstackVMs.groovy
> +	return UserMap
여기서 userMap은 비어있는 상태 아닌가요?  윗줄의 osUsername, osPassword가 map에 insert가 안된것처럼 보이네요.

2020-09-21 07:48 UTC, jacobbaek commented on createOpenstackVMs.groovy
> +	return UserMap
엇... 실수했네요 수정해서 업데이트 하겠습니다~

2020-09-23 01:25 UTC, robertchoi80 approved these changes

2020-09-23 01:26 UTC, merged